import Header from "@/components/header/header";
import './globals.css'
import { CartProvider } from "@/context";

export const metadata = {
  title: "eShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <body>
          <Header />
          {children}
        </body>
      </html>
    </CartProvider>
  );
}
